server {
    listen 80;
    listen 8080;
    listen 127.0.0.1:8080;
    listen 192.168.1.10:3000;
    listen localhost:8000;
    listen localhost;
    listen 10.0.0.5;
    listen 0.0.0.0:65535;
    listen 255.255.255.255:1;
    # listen abc;                # Uncomment to test error
    # listen 999.999.999.999:80; # Uncomment to test error
    # listen 127.0.0.1:99999;    # Uncomment to test error
    # listen :80;                # Uncomment to test error
    # listen 80abc;              # Uncomment to test error
}
