server {
    listen 80;
    listen 443;
    listen 127.0.0.1:8080;
    server_name example.com www.example.com;

    root /var/www/example.com;
    client_max_body_size 20m; 
    index index.html index.htm;

    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 500 502 503 504 /errors/50x.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /media/images/ {
        root /var/www/shared_data; 
        allow_methods GET;
        autoindex on;
    }

    location /api/ {
        allow_methods GET POST;
        client_max_body_size 5k; 
        index api_index.json; 
    }

    location /upload {
        allow_methods POST;
        client_max_body_size 50m; 
        upload_path /var/www/uploads;
    }

    location /scripts/php/ {
        root /var/www/cgi-scripts;
        allow_methods GET POST;
        cgi_pass .php /usr/bin/php-cgi;
    }
    
    location /scripts/python/ {
        root /var/www/cgi-scripts;
        allow_methods GET POST;

        location /scripts/python/special.py {
            cgi_pass .py /usr/bin/python3.9; 
        }
    }

    location /old-page.html {
        return 301 /new-page.html;
    }
}

server {
    listen 9090;
    server_name internal.service.local;

    root /var/www/internal_site;
    autoindex on; 

    location / {
        allow_methods GET POST DELETE;
        index status.html;
    }
}

server{
    listen 10000;
    server_name	test.machine;
    root		/tmp/www;
    location / {
        index test.txt;
    }
}