server{
    listen 8080;
    listen 8000;
    listen 4433;
    server_name	test.machine;
    root		/tmp/www;
    location / {
        index test.txt;
    }
}

# server {
#     listen 9090;
#     server_name internal.service.local;

#     root /var/www/internal_site;
#     autoindex on; 

#     location / {
#         allow_methods GET POST DELETE;
#         index status.html index.htl;
#         autoindex off;
#     }
# }