server {
    listen 8080;
    server_name tester;

    root www;
    index index.html;

    location / {
        allow_methods GET;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    location /directory {
        allow_methods GET POST;
        root cgi-scripts;
        cgi_pass .py .php .bla;
    }
}
